### ISSUE TITLE
No query type 'lint' defined

### ISSUE THREAD

**Issue by IshmaelBelghazi** [katspaugh/tern-lint.el#1]
I have copied lint.js in the plugin directory fo the tern distribution.  

Here is my .tern-project file:
```
{
    "libs": ["ecma5"],
    "loadEagerly": ["d3.js"],
    "plugins": {
        "node": {},
        "lint": {},
        "requirejs": {
            "baseURL": "./",
            "paths": {}
    }
  }
}
```
However, flycheck keeps returning the following error:

```
Request failed: ((error http 400) . No query type 'lint' defined)
```

**Comment by katspaugh** [comment]
Where is your `.tern-project` file located? It should be in the same (or upper) directory as your JS file is.

**Comment by IshmaelBelghazi** [comment]
It is in the same directory.

**Comment by katspaugh** [comment]
It seems Tern doesn't see your plugin. Did you install it locally or just copied the file to the Tern plugins directory?

**Comment by katspaugh** [comment]
Please read Tern plugin installation instructions here: http://ternjs.net/doc/manual.html#plugin_third_party

**Comment by IshmaelBelghazi** [comment]
I am running Ubuntu 15.04. I have copied the lint.js file in /usr/lib/nodes_modules/tern/plugin/. This is what I understood of the tern plugin instructions. Am I missing something?

**Comment by katspaugh** [comment]
Does `/usr/lib/nodes_modules/tern/plugin/` contain all the other Tern plugins, like `node.js` and `requirejs.js`?

**Comment by IshmaelBelghazi** [comment]
Yes it does. 

```
pwd                                                                                                                       12:11:11  2015-05-07 
/usr/lib/node_modules/tern/plugin
ls -altrh                                                                                                                 12:11:13  2015-05-07 
total 284K
-rw-r--r--  1 nobody ishmael 8.0K Jan 30 14:56 component.js
-rw-r--r--  1 nobody ishmael  15K Mar  2 05:28 requirejs.js
-rw-r--r--  1 nobody ishmael  15K Mar 25 07:28 doc_comment.js
-rw-r--r--  1 nobody ishmael 2.5K Mar 25 07:28 complete_strings.js
-rw-r--r--  1 nobody ishmael  46K Mar 25 07:28 angular.js
-rw-r--r--  1 nobody ishmael 163K Apr 10 06:54 node.js
drwxr-xr-x 10 nobody ishmael 4.0K May  5 16:00 ..
-rw-r--r--  1 root   root     18K May  5 16:02 lint.js
drwxr-xr-x  2 nobody ishmael 4.0K May  5 16:03 .
```

**Comment by katspaugh** [comment]
Weird. Try running the `tern` command inside your project's directory and add a console.log in `lint.js` to check that it is required.

**Comment by IshmaelBelghazi** [comment]
Interesting. 

```
tern                                                                                                                          14:46:00  2015-05-07 
I am lint.js
Listening on port 44819
```

**Comment by katspaugh** [comment]
When you have the server running like this, if you run the tern-lint command in Emacs, is it still complaining about not finding the lint query?

**Comment by IshmaelBelghazi** [comment]
I does work when the server is running.

**Comment by katspaugh** [comment]
Then I guess you might have another Tern installation somewhere else (besides `/use/lib`). Also make sure there are no other `.tern-project` files in your project tree. It might be using a `.tern-project` file that doesn't have the plugin listed.

**Comment by katspaugh** [comment]
To make sure Emacs starts the same server, set the `tern-command` to the Tern bin file path.

**Comment by IshmaelBelghazi** [comment]
Thanks a lot. It works now. I have set the term command to : 

```
(setq tern-command '("node" "/usr/bin/tern"))
```
